var TL=new Array();

/* 
Array of data for TOP LEFT screen (IAD Bidpartner)

TITLEMAIN,  (PAGE 2)
TITLE1 ,	etc.
TITLE2 ,
TITLE3 ,
TITLE4 ,
URL1
URL2
URL3
URL4
*/

/*
VERSIONS
8/9/1913  - created  -Eric Hetzel
9/25/1913 - renamed to TOP LEFT  -EH
9/25/1913 - removal of registrations and delivery  -EH
10/9/1913 - update of bidpartners (added Brightroll,cox,flurry,mopub)(removed tapit) -EH
4/28/1914 - update of bidparters (added Adap.tv, Valueclick) (removed Contextweb, Zenovia) - SM
*/



TL=[
//0
["IAD ALL AVAIL. BIDS 1/5",
"ADAP.TV",
"AOL",
"APPNEXUS",
"BRIGHTROLL",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD.*rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398179328818",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=AOL+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//1
["IAD ALL AVAIL. BIDS 2/5",
"BURST",
"CASALE",
"COX",
"DOUBLECLICK",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=BURST+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=COX+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_COX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908"],
//2
["IAD ALL AVAIL. BIDS 3/5",
"FACEBOOK",
"FLURRY",
"MOPUB",
"NEXAGE",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905"],
//3
["IAD ALL AVAIL. BIDS 4/5",
"OPENX",
"PUBMATIC",
"RMX",
"RUBICON",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=RMX+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905"],
//4
["IAD ALL AVAIL. BIDS 5/5",
"SPECIFIC",
"VALUECLICK",
"XAD",
"ZEDO",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD.*rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398715553762",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD.*rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988159",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtiad.*rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//5
["IAD ADAP.TV 1/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD01rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268133774",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD02rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385478",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD03rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385479",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD04rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385481"],
//6
["IAD AOL 2/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//7
["IAD APPNEXUS 3/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//8
["IAD BrightRoll 4/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//9
["IAD BURST 5/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//10
["IAD CASALE 6/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//11
["IAD COX 7/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+COX+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_COX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+COX+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_COX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+COX+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_COX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+COX+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_COX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//12
["IAD DOUBLECLICK 8/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//13
["IAD FACEBOOK 9/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//14
["IAD FLURRY 10/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//15
["IAD MOPUB 11/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//16
["IAD NEXAGE 12/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//17
["IAD OPENX 13/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//18
["IAD PUBMATIC 14/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//19
["IAD RMX 15/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//20
["IAD RUBICON 16/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//21
["IAD SPECIFIC 17/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//22
["IAD VALUECLICK 18/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD01rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988129",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD02rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988130",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD02rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988130",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD04rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988132"],
//23
["IAD XAD 19/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD01rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988160",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD02rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988161",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD03rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988162",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=IAD04rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988163"],
//24
["IAD ZEDO 20/20",
"IAD 01",
"IAD 02",
"IAD 03",
"IAD 04",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+01+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtiad01rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+02+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtiad02rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+03+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtiad03rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://iad.trend.int/graph.php?r=day&z=xlarge&title=IAD+04+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtiad04rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
]
