var BL=new Array();

/* 
Array of data for TOP LEFT screen (SJC Bidpartner)

TITLEMAIN,  (PAGE 2)
TITLE1 ,	etc.
TITLE2 ,
TITLE3 ,
TITLE4 ,
URL1
URL2
URL3
URL4
*/

/*
VERSIONS
8/9/2013  - created  -Eric Hetzel
9/25/2013 - renamed to BOTTOM LEFT  -EH
9/25/2013 - removal of registrations and delivery  -EH
10/9/2013 - update of bidpartners (added Brightroll,cox,flurry,mopub)(removed tapit) -EH
4/28/1914 - update of bidparters (added Adap.tv, Valueclick) (removed Contextweb, Zenovia) - SM
*/



BL=[
//0
["SJC ALL AVAIL. BIDS 1/5",
"ADAP.TV",
"AOL",
"APPNEXUS",
"BRIGHTROLL",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=ADAP.TV+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC.*rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988136",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=AOL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//1
["SJC ALL AVAIL. BIDS 2/5",
"BURST",
"CASALE",
"COX",
"DOUBLECLICK",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=BURST+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=COX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=cox_avail_bids&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908"],
//2
["SJC ALL AVAIL. BIDS 3/5",
"FACEBOOK",
"FLURRY",
"MOPUB",
"NEXAGE",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905"],
//3
["SJC ALL AVAIL. BIDS 4/5",
"OPENX",
"PUBMATIC",
"RMX",
"RUBICON",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=RMX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905"],
//4
["SJC ALL AVAIL. BIDS 5/5",
"SPECIFIC",
"VALUECLICK",
"XAD",
"ZEDO",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC.*rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988140",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC.*rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988167",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtsjc.*rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907",
],
//5
["SJC ADAP.TV 1/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC01rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385485",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC02rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385486",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=ADAP.TV+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC03rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988142",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=Adap.tv+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC04rtb.*&mreg[]=rtb_requests_available_ADAPTV&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398268385488"],
//6
["SJC AOL 2/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+AOL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_AOL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//7
["SJC APPNEXUS 3/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+APPNEXUS+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_APPNEXUS&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//8
["SJC BrightRoll 4/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+BRIGHTROLL+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_BRIGHTROLL&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//9
["SJC BURST 5/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+BURST+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_BURST&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//10
["SJC CASALE 6/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+CASALE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_CASALE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//11
["SJC COX 7/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+COX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=cox_avail_bids&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+COX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=cox_avail_bids&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+COX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=cox_avail_bids&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+COX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=cox_avail_bids&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//12
["SJC DOUBLECLICK 8/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+DOUBLECLICK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_DOUBLECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//13
["SJC FACEBOOK 9/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+FACEBOOK+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_FACEBOOK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//14
["SJC FLURRY 10/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+FLURRY+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_FLURRY&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//15
["SJC MOPUB 11/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+MOPUB+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_MOPUB&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//16
["SJC NEXAGE 12/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+NEXAGE+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_NEXAGE&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//17
["SJC OPENX 13/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+OPENX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=ss_rtb_requests_available_OPENX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//18
["SJC PUBMATIC 14/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+PUBMATIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_PUBMATIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//19
["SJC RMX 15/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+RMX+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_RMX&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//20
["SJC RUBICON 16/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+RUBICON+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_RUBICON&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//21
["SJC SPECIFIC 17/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+SPECIFIC+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_SPECIFIC&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
//22
["SJC VALUECLICK 18/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC01rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988144",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC02rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988147",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC03rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988146",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=VALUECLICK+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC04rtb.*&mreg[]=rtb_requests_available_VALUECLICK&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988148"],
//23
["SJC XAD 19/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC01rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988168",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC01rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988168",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC03rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988170",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=XAD+Available+Bids+Last+Day&vl=&x=&n=&hreg[]=SJC03rtb.*&mreg[]=rtb_requests_available_XAD&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1398786988170"],
//24
["SJC ZEDO 20/20",
"SJC 01",
"SJC 02",
"SJC 03",
"SJC 04",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+01+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtsjc01rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166905",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+02+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtsjc02rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166906",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+03+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtsjc03rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166908",
"http://sjc.trend.dc.dotomi.net/graph.php?r=day&z=xlarge&title=SJC+04+ZEDO+Available+Bids&vl=&x=&n=&hreg[]=dtsjc04rtb.*&mreg[]=rtb_requests_available_ZEDO&gtype=stack&glegend=hide&aggregate=1&embed=1&_=1375815166907"],
]
